name: Build - linux
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'tools/**'
      - 'docs/**'
      - '.vscode/**'
      - '.github/configs/**'
      - '**.md'
  pull_request:

jobs:
  ubuntu2204:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        is_clang: [ true, false ]
        # build_type: [ debug, release ]
        build_type: [ release ]
    container:
      image: ghcr.io/${{ github.repository_owner }}/ten_building_ubuntu2204:feature-ci
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: 'true'
      - name: Build
        run: |
          export PATH=$(pwd)/core/ten_gn:$PATH
          tgn gen linux x64 ${{ matrix.build_type }} -- is_clang=${{ matrix.is_clang }}
          tgn build linux x64 ${{ matrix.build_type }}
          tree out

  ubuntu1804:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ release ]
    container:
      image: ghcr.io/${{ github.repository_owner }}/ten_building_ubuntu1804:feature-ci
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
      - name: Build
        run: |
          export PATH=$(pwd)/core/ten_gn:$PATH
          tgn gen linux x64 ${{ matrix.build_type }} -- is_clang=false
          tgn build linux x64 ${{ matrix.build_type }}
          tree out
